all:
	pandoc --toc --number-sections -V geometry:margin=1in --csl=bibliography.csl \
    project-background.md docker.md docker-swarm.md cloudmesh.md project.md --bibliography report.bib refernces.bib \
    -o paper.pdf


# --template=template.latex \
